### ISSUE TITLE
Програма не виходить з циклу 

### ISSUE THREAD

**Issue by Muxamedin** [svlanas/python_hw_project#1]
https://github.com/svlanas/python_hw_project/blob/a75973c8ad3d24a508ecef9cb5b1f62f951af117/hw%206/find.py#L5
<img width="500" alt="image" src="https://user-images.githubusercontent.com/4419752/200426834-3246ec43-967f-47c7-b458-b5412bcb11a2.png">

**Comment by svlanas** [comment]
![image](https://user-images.githubusercontent.com/108218048/200496817-e6b86d58-e359-46a5-80a9-6a5d4b9c57a0.png)
Додано умову для виходу з циклу
